"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

export default function HomePage() {
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");

  async function handleAccept() {
    setIsLoading(true);
    setError("");

    try {
      const response = await fetch("/api/session", { method: "POST" });

      if (!response.ok) {
        const body = (await response.json()) as { error?: string };
        throw new Error(body.error || "Unable to start the session.");
      }

      const data = (await response.json()) as {
        sessionId: string;
        assignment: { batchNumber: number; totalBatches: number };
      };
      localStorage.setItem("participantSessionId", data.sessionId);
      localStorage.removeItem("studyState");
      localStorage.removeItem("studyQuestionnaire");
      localStorage.removeItem("studyResponses");
      router.push("/questionnaire");
    } catch (requestError) {
      setError(requestError instanceof Error ? requestError.message : "Something went wrong.");
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <main className="shell">
      <section className="panel hero">
        <p className="eyebrow">Research Study</p>
        <h1 className="title">Thank you for participating in our survey.</h1>
        <p className="lead">Please read the instructions and disclaimer below before continuing.</p>

        <article className="card">
          <h2>Instructions</h2>
          <p className="muted">
            On the next page of the survey, you will be asked to record information which may be relevant to
            your ability to classify videos as Artificial Intelligence Generated Content (AIGC) or videos
            recorded in the real world by a human person.
          </p>
          <p className="muted">
            On the subsequent pages, you will be timed while watching a video. You do not have to finish
            watching the entire video, and may pause the video or rewatch it to your discretion. When you feel
            confident that the video is either real or AIGC, click the appropriate box and press submit answer, and the timer will
            stop. You will be prompted to include anything that made you confident in your classification.
            After submitting a response to the prompt, a new video will be loaded and the timer will reset. A
            collection of ten videos have been selected at random for your specific participation. Once you
            have reviewed ten videos, your participation in the survey will be complete, and your data will be
            saved.
          </p>
          <p className="muted">
            Please only participate in the survey one time. Additional information gathered from users beyond
            the ten videos selected for them could skew the data from the survey. Additionally, please review
            these videos by yourself and without input from others.
          </p>
        </article>

        <article className="card">
          <h2>Disclaimer</h2>
          <p className="muted">
            Each of the videos you will see on this website were either fully generated by AI or were made
            with absolutely no AI tools. No videos were recorded and later modified by AI. These videos have
            been stripped of their metadata and shuffled into a random order. As you will only be seeing a
            subset of these videos, it is entirely possible that the collection of videos you see will have no
            AIGC, will be entirely AIGC, or some mixture of AIGC and real videos. No effort has been made to
            balance the ratio of AIGC and real videos you will see. All AIGC was made by prompts from the
            research team, and all real videos were recorded by the research team. No footage has been
            provided by external sources.
          </p>
          <p className="muted">
            This website and the affiliated materials have been created for research purposes. By completing
            this survey, you consent for the gathering of certain pieces of data and information as defined
            below to satisfy the affiliated research.
          </p>
          <p className="muted">
            The purpose of this survey is to collate data about the average person&apos;s ability to identify if
            a video has been generated by an Artificial Intelligence or recorded by a human person. To note,
            the results of the people who participated in the survey will be compared to publicly available
            AIGC detection tools. To this end, the recorded metrics include:
          </p>
          <ul className="study-list muted">
            <li>Accuracy in classification of each video.</li>
            <li>Elapsed time before a confident classification can be made for each video.</li>
            <li>Non-identifying personal data of the participant.</li>
          </ul>
          <p className="muted">
            The personal data recorded by this survey is designed to qualify your experience with AI to better
            categorize the performance of the average participant of the survey. It will be stored anonymously
            on an online database upon completion of the survey, and included in any publication of the
            related research.
          </p>
          <p className="muted">
            The information here will not be used to identify you in any way. It will not be sold to third
            parties for marketing purposes nor retained by the research team for use outside of this survey.
            No metadata or device analytics are being recorded by the research team; the only collected data
            is the self-reported information on the next page and the two aforementioned research metrics.
          </p>
          <p className="muted">
            By finishing the survey, you consent to have your self-reported data recorded to the aforementioned
            database along with your performance in categorizing the videos. If you do not wish to have your
            information recorded, simply leave this website and end your browser session at any time; data will
            not be recorded and submitted for the research until the final video has been reviewed. Incomplete
            data will be discarded.
          </p>
        </article>

        {error ? <p className="error">{error}</p> : null}

        <div className="actions">
          <button className="button button-primary" type="button" onClick={handleAccept} disabled={isLoading}>
            {isLoading ? "Starting..." : "Accept and continue"}
          </button>
        </div>
      </section>
    </main>
  );
}
